Task 1 Part 1

Generate matrices with help of randint

In [1]:
# Import Numpy
import numpy as np
# Define the 4 matrices as A,B,C,D
A = np.random.randint(1,10,(2,3))
B = np.random.randint(1,10,(3,5))
C = np.random.randint(1,10,(5,2))
D = np.random.randint(1,10,(3,3))
# Print the 4 matrices
print(A)
print(B)
print(C)
print(D)
# Find the Dot Product of matrices
E = np.dot(A,B)
F = np.dot(B,C)
#can't print invalid matrices
#G = np.dot(C,D)
#H = np.dot(D,A)
print(E)
print(F)
#print(G)
#print(H)

[[9 9 2]
 [3 4 6]]
[[1 9 4 1 8]
 [8 2 7 5 4]
 [2 1 3 8 1]]
[[7 6]
 [8 8]
 [2 4]
 [4 6]
 [8 8]]
[[6 3 3]
 [2 6 9]
 [4 2 7]]
[[ 85 101 105  70 110]
 [ 47  41  58  71  46]]
[[155 164]
 [138 154]
 [ 68  88]]


Task 1 part 2

Use shape tuple to access column and row number of matrices to check if dot product is possible.**bold text**

In [2]:
def is_compatible(A, B):
  if(A.shape[1]==B.shape[0]):
      print(np.dot(A,B))
      return
  else:
    print("Dimension Error!")
# Find Dot product only if the matrices are compatible
is_compatible(A,B)
is_compatible(B,C)
is_compatible(C,D)
is_compatible(D,A)

[[ 85 101 105  70 110]
 [ 47  41  58  71  46]]
[[155 164]
 [138 154]
 [ 68  88]]
Dimension Error!
Dimension Error!


Task 2

Input number of rounds and call function
Use while loop to check number of rounds left
input user's choice.
Use modulo 12 to ensure proper input
Randomize computers output using randint from numpy
use if else for scoring
break if points>=30 or <=-30


In [4]:
def up_down(rounds):
  points=0
  while(rounds>0):
    usernum=input("Enter a number between 1 and 12(inclusive)")
    usernum = int(usernum)%12
    compnum = np.random.randint(1,13)
    if(compnum>7):
      if(usernum>7):points+=usernum
      else:points-=usernum
    elif(compnum<7):
      if(usernum<7):points+=usernum
      else:points-=usernum
    else:
      if(usernum==7):points+=14
      else:points-=usernum
    if(points>=30):break
    elif(points<=-30):break
    rounds=rounds-1

  print(points)
  if(points>=30):print("You won!")
  elif(points<=-30):print("You lost!")
  else: print("You did well")

roundnum = input("Enter number of rounds")
up_down(int(roundnum))

Enter number of rounds3
Enter a number between 1 and 12(inclusive)1
Enter a number between 1 and 12(inclusive)1
Enter a number between 1 and 12(inclusive)2
4
You did well
