# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [16]:
# Import Numpy
import numpy as np

In [18]:
# Define the 4 matrices as A,B,C,D
A = np.random.randint(0, 11, size = (2,3))
B = np.random.randint(0, 11, size = (3,5))
C = np.random.randint(0, 11, size = (5,2))
D = np.random.randint(0, 11, size = (3,3))

In [9]:
# Print the 4 matrices
print(A)
print(B)
print(C)
print(D)

[[8 1 0]
 [3 5 9]]
[[10  4  2  1  9]
 [ 5  5  4  8  8]
 [ 1  6  1  4  4]]
[[10  7]
 [ 4  0]
 [ 6  5]
 [ 3  6]
 [10  8]]
[[ 5  5  4]
 [ 5 10  2]
 [ 0  8  3]]


In [10]:
# Find the Dot Product of matrices
print(np.dot(A,B))
print(np.dot(B,C))
print(np.dot(C,D))

[[ 85  37  20  16  80]
 [ 64  91  35  79 103]]
[[221 158]
 [198 167]
 [ 92  68]]


ValueError: shapes (5,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [21]:
def is_compatible(A, B):
    if A.shape[1] == B.shape[0]:
        return True
    else:
        return False

if is_compatible(A, B)==True:
  print(np.dot(A,B)) 
else:
  print("Dimension Error!!")
if is_compatible(B, C)==True:
  print(np.dot(B,C)) 
else:
  print("Dimension Error!!")
if is_compatible(C, D)==True:
  print(np.dot(C,D)) 
else:
  print("Dimension Error!!")

[[117  62  25  91 101]
 [121  79  27  90 101]]
[[ 73 107]
 [ 71 147]
 [ 76 175]]
Dimension Error!!


In [ ]:
# Find Dot product only if the matrices are compatible

# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [ ]:
import numpy as np

def up_down(rounds):
    points = 0  

    for _ in range(rounds):  
        x = int(input("Enter a number between 1 and 12: "))  
        if x < 1 or x > 12:
            print("Invalid input")
            continue
          
        guess = np.random.randint(1, 13)  
        if guess < 7:
            if x < 7:
                points += x
            else:
                points -= x
        elif guess == 7:
            if x == 7:
                points += 14
            else:
                points -= x
        else:  
            if x > 7:
                points += x
            else:
                points -= x

        if points > 30:
            print("win!")
            return
        elif points < -30:
            print("lose!")
            return

    print(f"Score: {points}")

# Get user input for rounds
rounds = int(input("Enter number of rounds: "))
up_down(rounds)


Score: -21
