# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [1]:
# Import Numpy
import numpy as np

In [2]:
# Define the 4 matrices as A,B,C,D
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[2,4,6,8,10],[1,3,5,7,9],[1,2,3,4,5]])
C=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
D=np.array([[5,4,3],[3,2,1],[7,6,5]])

In [4]:
# Print the 4 matrices
print(A,"\n")
print(B,"\n")
print(C,"\n")
print(D,"\n")

[[1 2 3]
 [4 5 6]] 

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [ 1  2  3  4  5]] 

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]] 

[[5 4 3]
 [3 2 1]
 [7 6 5]] 



In [8]:
# Find the Dot Product of matrices
d1=np.dot(A,B)
d2=np.dot(B,C)
print(d1,"\n",d2,"\n")

[[  7  16  25  34  43]
 [ 19  43  67  91 115]] 
 [[110 140]
 [ 95 120]
 [ 55  70]] 



# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [9]:
def is_compatible(A, B):
  if A.shape[1]==B.shape[0]:
    return True
  else:
    return False
  pass

In [10]:
# Find Dot product only if the matrices are compatible
if is_compatible(A,B):
  print(np.dot(A,B))
else:
  print("Dimension Error!!")

[[  7  16  25  34  43]
 [ 19  43  67  91 115]]


# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [17]:
import numpy as np
def up_down(rounds):
  points=0
  while(rounds!=0):
    a=int(input("Enter a number between 1 and 12: "))
    b=np.random.randint(1,12)
    print(f"Your number: {a} \nComputer's number: {b}")
    if b<7:
      if a<7:
        points+=a
      else:
        points-=a
    elif b==7:
      if a==7:
        points+=14
      else:
        points-=a
    else:
      if a>7:
        points+=a
      else:
        points-=a
    print(f"Your points: {points}")
    rounds-=1
    if points>=30:
      print(f"You won! Final points: {points}")
      break
    elif points<=-30:
      print(f"You lost! Final points: {points}")
      break
    elif rounds==0:
      print(f"Out of rounds! Final points: {points}")
      break
  pass