# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [ ]:
import numpy as np

In [ ]:
array=np.array({(2,3),(3,5),(5,2),(3,3)})

In [ ]:
print("Printing the array:",array)

Printing the array: {(2, 3), (3, 3), (3, 5), (5, 2)}


In [ ]:
A=np.arange(6).reshape((2,3))
B=np.arange(15).reshape((3,5))
C=np.arange(10).reshape((5,2))
D=np.arange(9).reshape((3,3))
print(f"Matrix A (shape {A.shape}):\n{A}\n")
print(f"Matrix B (shape {B.shape}):\n{B}\n")
print(f"Matrix C (shape {C.shape}):\n{C}\n")
print(f"Matrix D (shape {D.shape}):\n{D}\n")
AB = np.dot(A, B)
print(f"Dot product of A and B (shape {AB.shape}):\n{AB}\n")
BC = np.dot(B, C)
print(f"Dot product of B and C (shape {BC.shape}):\n{BC}\n")
CD = np.dot(C, D)
print(f"Dot product of C and D (shape {CD.shape}):\n{CD}\n")

Matrix A (shape (2, 3)):
[[0 1 2]
 [3 4 5]]

Matrix B (shape (3, 5)):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Matrix C (shape (5, 2)):
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix D (shape (3, 3)):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Dot product of A and B (shape (2, 5)):
[[ 25  28  31  34  37]
 [ 70  82  94 106 118]]

Dot product of B and C (shape (3, 2)):
[[ 60  70]
 [160 195]
 [260 320]]



ValueError: shapes (5,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [ ]:
import numpy as np
array=np.array({(2,3),(3,5),(5,2),(3,3)})
print("Printing the array:",array)

Printing the array: {(2, 3), (3, 3), (3, 5), (5, 2)}


In [ ]:
def is_compatible(A, B):
    if A.shape[1] == B.shape[0]:
        result = np.dot(A, B)
        print(f"Dot product result (shape {result.shape}):\n{result}\n")
    else:
        print("Dimension Error!!")
A = np.arange(6).reshape((2, 3))
B = np.arange(15).reshape((3, 5))
C = np.arange(10).reshape((5, 2))
D = np.arange(9).reshape((3, 3))
print(f"Matrix A (shape {A.shape}):\n{A}\n")
print(f"Matrix B (shape {B.shape}):\n{B}\n")
print(f"Matrix C (shape {C.shape}):\n{C}\n")
print(f"Matrix D (shape {D.shape}):\n{D}\n")
print("A * B:")
is_compatible(A, B)
print("B * C:")
is_compatible(B, C)
print("C * D:")
is_compatible(C, D)
print("A * D:")
is_compatible(A, D)

Matrix A (shape (2, 3)):
[[0 1 2]
 [3 4 5]]

Matrix B (shape (3, 5)):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Matrix C (shape (5, 2)):
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix D (shape (3, 3)):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

A * B:
Dot product result (shape (2, 5)):
[[ 25  28  31  34  37]
 [ 70  82  94 106 118]]

B * C:
Dot product result (shape (3, 2)):
[[ 60  70]
 [160 195]
 [260 320]]

C * D:
Dimension Error!!
A * D:
Dot product result (shape (2, 3)):
[[15 18 21]
 [42 54 66]]



# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [ ]:
import random

def up_down_game(round_limit):
    total_score = 0

    def get_player_guess():
        while True:
            try:
                player_number = int(input("Pick a number between 1 and 12: "))
                if 1 <= player_number <= 12:
                    return player_number
                else:
                    print("Oops! Please enter a number between 1 and 12.")
            except ValueError:
                print("Invalid input! Please enter a whole number.")

    def calculate_score(player_number, computer_number, current_score):
        if (computer_number < 7 and player_number < 7) or (computer_number > 7 and player_number > 7):
            print(f"Nice! You guessed the correct range. You get {player_number} points.")
            return current_score + player_number
        elif computer_number == 7 and player_number == 7:
            print("Wow! Exact match! You get 14 points.")
            return current_score + 14
        else:
            print(f"Oops! Wrong range. You lose {player_number} points.")
            return current_score - player_number

    for round_number in range(1, round_limit + 1):
        print(f"Round {round_number}")
        player_number = get_player_guess()
        computer_number = random.randint(1, 12)

        print(f"The computer picked: {computer_number}")
        total_score = calculate_score(player_number, computer_number, total_score)

        print(f"Your current score: {total_score}\n")

        if total_score > 30:
            print("Congratulations! You win the game!")
            break
        elif total_score < -30:
            print("Game over! Better luck next time.")
            break

    print(f"Game over! Your final score is: {total_score}")


if __name__ == "__main__":
    rounds = int(input("Enter the number of rounds you want to play: "))
    up_down_game(rounds)
