# **Task 1**

Your goal is to find the answer of the dot product of the matrices of sizes (2,3), (3,5), (5,2) and (3,3).

## **Workflow:**
1. Define the matrices of given sizes.
2. Print the matrices.
3. Use the np.dot function.
4. Print the output at each step.
5. Print the result.

(Print the shape of matrix always with the matrix)


In [2]:
import numpy as np
# Import Numpy

In [3]:
A = np.random.rand(2, 3)
B = np.random.rand(3, 5)
C = np.random.rand(5, 2)
D = np.random.rand(3, 3)
# Define the 4 matrices as A,B,C,D

In [4]:
print("Matrix A (2, 3):")
print(A)
print("Shape of A:", A.shape)

print("\nMatrix B (3, 5):")
print(B)
print("Shape of B:", B.shape)

print("\nMatrix C (5, 2):")
print(C)
print("Shape of C:", C.shape)

print("\nMatrix D (3, 3):")
print(D)
print("Shape of D:", D.shape)
# Print the 4 matrices

Matrix A (2, 3):
[[0.76104684 0.52365407 0.78922675]
 [0.17004762 0.52681392 0.36138411]]
Shape of A: (2, 3)

Matrix B (3, 5):
[[0.97068368 0.44807126 0.90625223 0.91989902 0.24348075]
 [0.24442811 0.99502671 0.47511115 0.86110663 0.90940304]
 [0.98454353 0.48891307 0.93908981 0.4412823  0.125026  ]]
Shape of B: (3, 5)

Matrix C (5, 2):
[[0.26544127 0.35096461]
 [0.57721038 0.93361404]
 [0.17189198 0.94802647]
 [0.76431342 0.3171631 ]
 [0.72889671 0.37173525]]
Shape of C: (5, 2)

Matrix D (3, 3):
[[0.06177151 0.19925334 0.32783258]
 [0.59357376 0.24013472 0.15555073]
 [0.91747788 0.11960292 0.48476895]]
Shape of D: (3, 3)


In [14]:
# Find the Dot Product of matrices
mat1=np.dot(A,D)
print("mat1 is" , mat1)
mat2=np.dot(mat1,B)
print("mat2 is" , mat2)
mat3=np.dot(mat2,C)
print("mat3/result is" , mat3)

mat1 is [[1.08193641 0.37178247 0.71354334]
 [0.65476895 0.20361146 0.31288123]]
mat2 is [[1.84360659 1.20357876 1.82722656 1.63029064 0.69074226]
 [0.99338709 0.64895371 0.98394747 0.91572144 0.3837068 ]]
mat3/result is [[3.2477058  4.27681912]
 [1.78698224 2.32039465]]


# ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Now the task is to define a function named is_compatible() that takes 2 matrices as input and only allows the dot product if the condition number of **columns** in the first matrix (A) matches the number of **rows** in the second matrix (B).

Print the ouput if condition is satisfied
Else print "Dimension Error!!"




In [42]:
import numpy as np
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6, 7], [8, 9, 10]])

def is_compatible(mat1, mat2):
 if mat1.shape[1]==mat2.shape[0]:
  print("Condition is satisfied")
 else:
  print("Dimension Error!!")

is_compatible(mat1, mat2)

Condition is satisfied


In [44]:
sol=np.dot(mat1,mat2)
print("sol is" , sol)
# Find Dot product only if the matrices are compatible

sol is [[21 24 27]
 [47 54 61]]


# **Task 2**

Your goal is to define a function that simulates a number-guessing game called "Up-Down." The function, named up_down, should take an integer rounds as input, representing the number of turns the player gets.

Game Rules:

1. The player inputs a number between 1 and 12 for each round.
2. The computer randomly selects a number between 1 and 12.
3. The scoring system is as follows:
  
  a. If computer's guess is less than 7 and the player gains points equivalent to their guess if their guess is also less than 7, otherwise, they lose points equivalent to their guess.
  
  b. If computer's guess is exactly 7, the player gains 14 points if thier guess is 7, otherwise, they lose points equivalent to their guess.
  
  c. If computer's guess is greater than 7 and the player gains points equivalent to their guess if their guess is also greater than 7, otherwise, they lose points equivalent to their guess.

4. The game continues until:

  a. The player reaches more than 30 points, they win.

  b. The player reaches less than -30 points, they lose.

  c. The maximum number of rounds is reached.
  
At the end of the game, the function should print the final score.

Your task is to implement this function in Python using the given rules.

In [53]:
import random

def up_down(rounds):
    score = 0

    for roundnum in range(0, rounds):
        player = int(input(f"Round {roundnum}: Guess a number between 1 and 12: "))


        comp = random.randint(1, 12)

        print(f"Computer's guess: {comp}")

        if comp < 7:
            if player < 7:
                score += player
                print(f"You gain {player} points!")
            else:
                score -= player
                print(f"You lose {player} points!")
        elif comp == 7:
            if player == 7:
                score += 14
                print("You gain 14 points!")
            else:
                score -= player
                print(f"You lose {player} points!")
        else:
            if player > 7:
                score += player
                print(f"You gain {player} points!")
            else:
                score -= player
                print(f"You lose {player} points!")

        if score > 30:
            print(f"You win with a score of {score}!")
            return
        elif score < -30:
            print(f"You lose with a score of {score}!")
            return

        print(f"Your current score: {score}\n")

    print(f"Game over! Final score: {score}")

user_input = int(input("Enter the number of rounds: "))
up_down(user_input)


Enter the number of rounds: 2
Round 0: Guess a number between 1 and 12: 7
Computer's guess: 8
You lose 7 points!
Your current score: -7

Round 1: Guess a number between 1 and 12: 7
Computer's guess: 7
You gain 14 points!
Your current score: 7

Game over! Final score: 7
